version: '3.7'
services:
  # MASTER
  redis-master:
    build: 
      context: ./redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  
  # replicas
  redis-replica1:
    build: 
      context: ./redis
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof redis-master 6379
    depends_on:
      - redis-master

  redis-replica2:
    build: 
      context: ./redis
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof redis-master 6379
    depends_on:
      - redis-master
  
  # GUI
  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - 7843:7843
    depends_on:
      - redis-master
    volumes:
      - ./p3x-redis-ui-settings:/settings
  
  # SENTINELS
  redis-sentinel1:
    build: 
      context: ./redis-sentinel
    ports:
      - "26379:26379"
    links:
      - redis-master
 
  redis-sentinel2:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
 
  redis-sentinel3:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master

  redis-demo:
    build:
      context: ./redis-demo
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2
      - redis-sentinel1
      - redis-sentinel2
      - redis-sentinel3
